server {
    listen 8088;
    server_name localhost;
    
    location / {
        root /Users/mrtun/Documents/Opinion\ Collector\ System/appV2/Projects/opinion-collector/frontend;
        try_files $uri $uri/ /pages/login.html;
        index pages/login.html;
    }
    
    location /api/ {
        proxy_pass http://localhost:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
    
    location /uploads/ {
        proxy_pass http://localhost:3000/uploads/;
    }
}
